name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install tools
        run: python -m pip install --upgrade pip ruff

      - name: Lint (non-blocking for now)
        run: ruff check . --exit-zero

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install project under test (resume_optimiser)
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e crew/resume_optimiser
          python -m pip install pytest

      - name: Run tests
        run: pytest -q crew/resume_optimiser/tests
